const CATALOG_VERSION = "excel-2026-06-14";
const baseProducts = [
  {
    "id": "excel-1",
    "title": "DOWNY BRISA DE VERANO 350 ML",
    "category": "Lavanderia",
    "detail": "Suavizante \u00b7 Marca: Downy \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": true,
    "image": "goesca photos/18-1.png",
    "code": "SUAVIZANTE",
    "stock": 6
  },
  {
    "id": "excel-2",
    "title": "DOWNY BRISA INTENSA 350 ML",
    "category": "Lavanderia",
    "detail": "Suavizante \u00b7 Marca: Downy \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": true,
    "image": "goesca photos/18-1.png",
    "code": "SUAVIZANTE",
    "stock": 6
  },
  {
    "id": "excel-3",
    "title": "SUAVISANTE SOFT CLASICO DOY PACK 900ML",
    "category": "Lavanderia",
    "detail": "Suavizante \u00b7 Marca: Soft \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": true,
    "image": "goesca photos/23-1-600x600.png",
    "code": "SUAVIZANTE",
    "stock": 12
  },
  {
    "id": "excel-4",
    "title": "SUAVISANTE SOFT 1 LITRO",
    "category": "Lavanderia",
    "detail": "Suavizante \u00b7 Marca: Soft \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1890,
    "before": 1890,
    "discount": "",
    "hotSale": true,
    "image": "goesca photos/23-1-600x600.png",
    "code": "SUAVIZANTE",
    "stock": 12
  },
  {
    "id": "excel-5",
    "title": "SWAN RENDIDOR 50M X 4UN (MANGA 8 UN)",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Swan \u00b7 Stock: 2 \u00b7 Proveedor: Casanova",
    "price": 17990,
    "before": 17990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1004222-swan_de_4.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 2
  },
  {
    "id": "excel-6",
    "title": "NOBLE 50M X 4UN",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Noble \u00b7 Stock: 2 \u00b7 Proveedor: Casanova",
    "price": 17990,
    "before": 17990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000000697854-UN-01.jpg.webp",
    "code": "PAPEL HIGIENICO",
    "stock": 2
  },
  {
    "id": "excel-7",
    "title": "SWAN PREMIUN 200 MTS X 2 (DOBLE HOJA)",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: Swan \u00b7 Stock: 4 \u00b7 Proveedor: Casanova",
    "price": 10990,
    "before": 10990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1004222-swan_de_4.jpg",
    "code": "TOALLA ROLLO",
    "stock": 4
  },
  {
    "id": "excel-8",
    "title": "SWAN SMART 250 MTS X 2",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: Swan \u00b7 Stock: 4 \u00b7 Proveedor: Casanova",
    "price": 9990,
    "before": 9990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1004222-swan_de_4.jpg",
    "code": "TOALLA ROLLO",
    "stock": 4
  },
  {
    "id": "excel-9",
    "title": "REXONA BARRA HOMBRE INVISIBLE",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_875909-MLC95610382064_102025-T.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-10",
    "title": "REXONA BARRA HOMBRE V8",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Desodorante-Rexona-Caballero-V8-Protecci-n-Seca-Y-Fresca-Barra-45g-1-92920.jpg.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-11",
    "title": "REXONA BARRA HOMBRE XTRACOOL",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/rexona_20805036_2.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-12",
    "title": "REXONA SPRAY MEN V8",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Desodorante-Rexona-Caballero-V8-Protecci-n-Seca-Y-Fresca-Barra-45g-1-92920.jpg.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-13",
    "title": "REXONA SPRAY MEN XTRACOOL",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/rexona_20805036_2.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-14",
    "title": "REXONA SPRAY MUJER ACTIVE EMOTION",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_2X_964160-MLC48631967072_122021-F.jpg",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-15",
    "title": "REXONA SPRAY MUJER POWER DRY",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_860323-MLC93541734600_102025-O.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-16",
    "title": "REXONA BARRA DAMA BAMBU",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Rexona-Desodorante-Bamboo-Aloe-Vera-72-de-Proteccion-contiene-50g.png",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-17",
    "title": "REXONA BARRA DAMA INVISIBLE",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_875909-MLC95610382064_102025-T.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-18",
    "title": "REXONA BARRA DAMA POWER DRY",
    "category": "Higiene personal",
    "detail": "Desodorantes \u00b7 Marca: Rexona \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_860323-MLC93541734600_102025-O.webp",
    "code": "DESODORANTES",
    "stock": 6
  },
  {
    "id": "excel-19",
    "title": "BIO FRESCURA 800g",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Bio \u00b7 Stock: 18 \u00b7 Proveedor: Casanova",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-azul-Brillex-600x600.jpg",
    "code": "DETERGENTE",
    "stock": 18
  },
  {
    "id": "excel-20",
    "title": "BRILLINA AMARILLA 340 CC",
    "category": "Otros",
    "detail": "Cera \u00b7 Marca: Brilina \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Lustramuebles-Crema-Virginia-Tradicional-250.png",
    "code": "CERA",
    "stock": 12
  },
  {
    "id": "excel-21",
    "title": "BRILLINA ROJA 340 CC",
    "category": "Otros",
    "detail": "Cera \u00b7 Marca: Brilina \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Lustramuebles-Crema-Virginia-Tradicional-250.png",
    "code": "CERA",
    "stock": 12
  },
  {
    "id": "excel-22",
    "title": "CIF BA\u00d1O 450ml",
    "category": "Bano",
    "detail": "Doy Pack \u00b7 Marca: Cif \u00b7 Stock: 15 \u00b7 Proveedor: Casanova",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/cif-limpiador-bano-recarga-450-cc-puntolimpieza-32030.jpg.webp",
    "code": "DOY PACK",
    "stock": 15
  },
  {
    "id": "excel-23",
    "title": "CIF CREMA 375g",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Cif \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/banoycocina-44.jpg.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-24",
    "title": "CLORINDA 1L",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Clorinda \u00b7 Stock: 15 \u00b7 Proveedor: Casanova",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/09090201.jpeg",
    "code": "LIMPIEZA",
    "stock": 15
  },
  {
    "id": "excel-25",
    "title": "CLOROX 5 EN 1 X1LT",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Clorox \u00b7 Stock: 15 \u00b7 Proveedor: Casanova",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/clx-cl-bleach-thin-original-front-1000g-7805025110009_NI-64563.png.avif",
    "code": "LIMPIEZA",
    "stock": 15
  },
  {
    "id": "excel-26",
    "title": "ALMACENERO 50M X 48UN",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Confort \u00b7 Stock: 1 \u00b7 Proveedor: Casanova",
    "price": 24000,
    "before": 24000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/papel-higienico-confort-1hoja-almacenero-50mt-und.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 1
  },
  {
    "id": "excel-27",
    "title": "ESPONJA ACANALADA ECO X 50UN",
    "category": "Cocina",
    "detail": "Esponja \u00b7 Marca: Dom \u00b7 Stock: 1 \u00b7 Proveedor: Casanova",
    "price": 10000,
    "before": 10000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/images.jpeg",
    "code": "ESPONJA",
    "stock": 1
  },
  {
    "id": "excel-28",
    "title": "ESPONJA LISA MULTIUSO X4 X 32UN",
    "category": "Cocina",
    "detail": "Esponja \u00b7 Marca: Impeke \u00b7 Stock: 1 \u00b7 Proveedor: Casanova",
    "price": 7920,
    "before": 7920,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/images.jpeg",
    "code": "ESPONJA",
    "stock": 1
  },
  {
    "id": "excel-29",
    "title": "PLATA X3 x 10 UN",
    "category": "Cocina",
    "detail": "Esponja \u00b7 Marca: Manlac \u00b7 Stock: 1 \u00b7 Proveedor: Casanova",
    "price": 11900,
    "before": 11900,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping.jpeg",
    "code": "ESPONJA",
    "stock": 1
  },
  {
    "id": "excel-30",
    "title": "LIMPIAPISO 900ml PRIMAVERA",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Excell \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/PRODUCTOS-WEB-5-22.png",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-31",
    "title": "GUANTE AMARILLO T/L",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Manlac \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-32",
    "title": "CLOROGEL 900ml LAVANDA",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Igenix \u00b7 Stock: 10 \u00b7 Proveedor: Casanova",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/09090201.jpeg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-33",
    "title": "CLOROGEL 900ml TRADICIONAL",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Impeke \u00b7 Stock: 10 \u00b7 Proveedor: Casanova",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/09090201.jpeg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-34",
    "title": "LANA (VIRUTILLA DE PISO) X 25 UN",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Manlac \u00b7 Stock: 1 \u00b7 Proveedor: Casanova",
    "price": 6250,
    "before": 6250,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping.jpeg",
    "code": "LIMPIEZA",
    "stock": 1
  },
  {
    "id": "excel-35",
    "title": "LAVALOZA QUIX 480ml BOTELLA",
    "category": "Cocina",
    "detail": "Limpieza \u00b7 Marca: Quix \u00b7 Stock: 15 \u00b7 Proveedor: Casanova",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000401870001-UN-02.jpg.webp",
    "code": "LIMPIEZA",
    "stock": 15
  },
  {
    "id": "excel-36",
    "title": "LAVALOZA QUIX 480ml",
    "category": "Cocina",
    "detail": "Doy Pack \u00b7 Marca: Quix \u00b7 Stock: 15 \u00b7 Proveedor: Casanova",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000401870001-UN-02.jpg.webp",
    "code": "DOY PACK",
    "stock": 15
  },
  {
    "id": "excel-37",
    "title": "LIMPIADOR DE HORNOS 400 ML",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Teddy \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Limpiador-Sacagrasa-Horno-Parrilla-y-Cocina-Teddy-400-ml_resultado.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-38",
    "title": "OMO PARA DILUIR PIEL SENCIBLE 500ml",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Omo \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 4790,
    "before": 4790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_777388-MLA99291234898_112025-F.webp",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-39",
    "title": "OMO PARA DILUIR POWER ULTRA 500ml",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Omo \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 4790,
    "before": 4790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_777388-MLA99291234898_112025-F.webp",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-40",
    "title": "ENJUAGUE BUCAL MENTA FRESCA 250 ml",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Oral Fresch \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/7800004000302.png",
    "code": "BUCAL",
    "stock": 6
  },
  {
    "id": "excel-41",
    "title": "ENJUAGUE BUCAL MENTA FUERTE 250 ml",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Oral Fresch \u00b7 Stock: 6 \u00b7 Proveedor: Casanova",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/7800004000302.png",
    "code": "BUCAL",
    "stock": 6
  },
  {
    "id": "excel-42",
    "title": "PA\u00d1O ESPONJA X3",
    "category": "Cocina",
    "detail": "Limpieza \u00b7 Marca: Optimo \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/images.jpeg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-43",
    "title": "PA\u00d1O MICROFIBRA",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 25 \u00b7 Proveedor: Casanova",
    "price": 500,
    "before": 500,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Unknown.jpeg",
    "code": "LIMPIEZA",
    "stock": 25
  },
  {
    "id": "excel-44",
    "title": "PA\u00d1UELO DESECHABLE X18 DISPLAY",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Elite \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 3590,
    "before": 3590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/elite-pa6296.jpg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-45",
    "title": "PA\u00d1UELO ELITE FACIAL DISNEY PACK X36",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Elite \u00b7 Stock: 36 \u00b7 Proveedor: Casanova",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/elite-pa6296.jpg",
    "code": "LIMPIEZA",
    "stock": 36
  },
  {
    "id": "excel-46",
    "title": "SHAMPOO BOTELLA 750ml SURTIDO",
    "category": "Higiene personal",
    "detail": "Shampoo \u00b7 Marca: Ballerina \u00b7 Stock: 24 \u00b7 Proveedor: Casanova",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/SH-GRANADA.png",
    "code": "SHAMPOO",
    "stock": 24
  },
  {
    "id": "excel-47",
    "title": "TRAPERO MICROFIBRA CON OJAL",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 25 \u00b7 Proveedor: Casanova",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-49-350x350-1.jpg",
    "code": "LIMPIEZA",
    "stock": 25
  },
  {
    "id": "excel-48",
    "title": "BLANCO 300 ml",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Vanish \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Quitamanchas-Clorox-Ropa-Blanca-Polvo-90-g.jpg.webp",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-49",
    "title": "ROSADO 300ml",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Vanish \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/878100-vanish_color_polvo.jpg",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-50",
    "title": "CREMA DE 750g",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Wyn \u00b7 Stock: 12 \u00b7 Proveedor: Casanova",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Limpiador-Crema-Wyn-750-g.jpg.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-51",
    "title": "DESINFECTANTE IGENIX 360 ml",
    "category": "Ambientales",
    "detail": "Limpieza \u00b7 Marca: Igenix \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 2690,
    "before": 2690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/x-7805040000699-limpieza-de-espacios-desodorante-ambiental-desinfectante-igenix-vainilla-360cm3-puntobarato36783046.png",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-52",
    "title": "PASTA COLGATE T/A 75g CX 72",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Colgate \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/133959_PASTA-DENTAL-COLGATE-TRIPLE-ACCION-75ML.jpg",
    "code": "BUCAL",
    "stock": 12
  },
  {
    "id": "excel-53",
    "title": "PASTA COLGATE KIDS CX 24",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Colgate \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_611711-MLC92295719982_092025-O.webp",
    "code": "BUCAL",
    "stock": 12
  },
  {
    "id": "excel-54",
    "title": "CEPILLO DENTAL NI\u00d1O TIRA X12",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Essere \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 7080,
    "before": 7080,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cepillo-dental-Colgate-Super-Frexi-charcoal-600x600.jpg",
    "code": "BUCAL",
    "stock": 1
  },
  {
    "id": "excel-55",
    "title": "VIRUTILA PLATEADA TEDDY 25 UN X BOL",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Teddy \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 6250,
    "before": 6250,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping.jpeg",
    "code": "LIMPIEZA",
    "stock": 1
  },
  {
    "id": "excel-56",
    "title": "CEPILLO COLGATE CHARCOL TIRA X 24",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Colgate \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 7080,
    "before": 7080,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cepillo-dental-Colgate-Super-Frexi-charcoal-600x600.jpg",
    "code": "BUCAL",
    "stock": 1
  },
  {
    "id": "excel-57",
    "title": "LUSTRA MUEBLES FRASCO 250 ml",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Virginia \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Lustramuebles-Crema-Virginia-Tradicional-250.png",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-58",
    "title": "INSECTICIDA TANAX 390 ml",
    "category": "Otros",
    "detail": "Insecticida \u00b7 Marca: Tanax \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1990,
    "before": 1990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_884086-MLA81601807146_012025-O.webp",
    "code": "INSECTICIDA",
    "stock": 12
  },
  {
    "id": "excel-59",
    "title": "AMBIENTADOR BRILLEX 400ml X 12",
    "category": "Ambientales",
    "detail": "Aromatizante \u00b7 Marca: Brillex \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Ambiental-Brillex-Lavanda.jpg",
    "code": "AROMATIZANTE",
    "stock": 12
  },
  {
    "id": "excel-60",
    "title": "QUITAMACHA CLOROX POLVO 30g X10 UN",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Clorox \u00b7 Stock: 2 \u00b7 Proveedor: Nabil Nasser",
    "price": 5000,
    "before": 5000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/878100-vanish_color_polvo.jpg",
    "code": "LIMPIEZA",
    "stock": 2
  },
  {
    "id": "excel-61",
    "title": "SACHET MIXTO 24 UN BOLS",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Vanish \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 12000,
    "before": 12000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/878100-vanish_color_polvo.jpg",
    "code": "LIMPIEZA",
    "stock": 1
  },
  {
    "id": "excel-62",
    "title": "ESPONJA ACANALADA 50 UN",
    "category": "Cocina",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 10000,
    "before": 10000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/images.jpeg",
    "code": "LIMPIEZA",
    "stock": 1
  },
  {
    "id": "excel-63",
    "title": "SHICK TITANIUM HOMBRE 4 HOJAS",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Shick \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 11880,
    "before": 11880,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_611711-MLC92295719982_092025-O.webp",
    "code": "BELLEZA",
    "stock": 1
  },
  {
    "id": "excel-64",
    "title": "SHICK TITANIUM MUJER 4 HOJAS",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Shick \u00b7 Stock: 1 \u00b7 Proveedor: Nabil Nasser",
    "price": 11880,
    "before": 11880,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_611711-MLC92295719982_092025-O.webp",
    "code": "BELLEZA",
    "stock": 1
  },
  {
    "id": "excel-65",
    "title": "MOPA PLANA MICROFIBRA C/MANGO",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Aileda \u00b7 Stock: 2 \u00b7 Proveedor: Nabil Nasser",
    "price": 6990,
    "before": 6990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-148-430x430.jpg",
    "code": "LIMPIEZA",
    "stock": 2
  },
  {
    "id": "excel-66",
    "title": "VERDE NORMAL 8 UN",
    "category": "Otros",
    "detail": "Higiene Personal \u00b7 Marca: Ladysoft \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_875909-MLC95610382064_102025-T.webp",
    "code": "HIGIENE PERSONAL",
    "stock": 24
  },
  {
    "id": "excel-67",
    "title": "ROSADA X7 24 UN",
    "category": "Otros",
    "detail": "Higiene Personal \u00b7 Marca: Ladysoft \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_860323-MLC93541734600_102025-O.webp",
    "code": "HIGIENE PERSONAL",
    "stock": 24
  },
  {
    "id": "excel-68",
    "title": "NOCTURNA MALLA 7 UN",
    "category": "Otros",
    "detail": "Higiene Personal \u00b7 Marca: Ladysoft \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_860323-MLC93541734600_102025-O.webp",
    "code": "HIGIENE PERSONAL",
    "stock": 24
  },
  {
    "id": "excel-69",
    "title": "COTONITOS 200 UN",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Brillex \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cotonitos-200-600x600.jpg",
    "code": "BELLEZA",
    "stock": 24
  },
  {
    "id": "excel-70",
    "title": "PETALOS SWISS CHICO 50 UN",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Swiss \u00b7 Stock: 60 \u00b7 Proveedor: Nabil Nasser",
    "price": 690,
    "before": 690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/X_petalosdesmaquillantes8111.jpg",
    "code": "BELLEZA",
    "stock": 60
  },
  {
    "id": "excel-71",
    "title": "PROTECTOR DARIO 20UN",
    "category": "Otros",
    "detail": "Higiene Personal \u00b7 Marca: Ladysoft \u00b7 Stock: 30 \u00b7 Proveedor: Nabil Nasser",
    "price": 790,
    "before": 790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_860323-MLC93541734600_102025-O.webp",
    "code": "HIGIENE PERSONAL",
    "stock": 30
  },
  {
    "id": "excel-72",
    "title": "JABON POPEYE 170g",
    "category": "Higiene personal",
    "detail": "Limpieza \u00b7 Marca: Popeye \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/jabon-liquido-avena-web-300x300.jpg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-73",
    "title": "BIO FRESCURA 3L FRASCO",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Bio \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 5990,
    "before": 5990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-Liquido-Bio-Frescura-Campos-de-Hielo-3-L.jpg.webp",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-74",
    "title": "LAVALOZA VIRGINIA 500 ml FRASCO",
    "category": "Cocina",
    "detail": "Limpieza \u00b7 Marca: Virginia \u00b7 Stock: 15 \u00b7 Proveedor: Nabil Nasser",
    "price": 1690,
    "before": 1690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/5597a252-8a75-420f-a96d-b968bba868c0.ab10750db356cd71588759c217dfdfe6.jpeg.avif",
    "code": "LIMPIEZA",
    "stock": 15
  },
  {
    "id": "excel-75",
    "title": "LAVALOZA 1000ml",
    "category": "Cocina",
    "detail": "Doy Pack \u00b7 Marca: Virginia \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1890,
    "before": 1890,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000401870001-UN-02.jpg.webp",
    "code": "DOY PACK",
    "stock": 12
  },
  {
    "id": "excel-76",
    "title": "SACA GRASA 500 ml GATILLO",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Sacagrasa-Brillex.jpg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-77",
    "title": "LIMPIA VIDRIOS 500 ml GATILLO",
    "category": "Vidrios",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping-1.jpeg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-78",
    "title": "CLORO GEL 900 ML FRASCO",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/09090201.jpeg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-79",
    "title": "TRAPERO HUMEDO BRILLEX 7UN X BOLSA",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/010309-BRILLEX-TRAPERO-HUMEDO-LIMON-7-UNID.jpg.avif",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-80",
    "title": "LIMPIADOR DE PISO BRILLEX 900 ml FRASCO",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/PRODUCTOS-WEB-5-22.png",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-81",
    "title": "CLORINDA 500 ML FRASCO",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Clorinda \u00b7 Stock: 28 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000401870001-UN-02.jpg.webp",
    "code": "LIMPIEZA",
    "stock": 28
  },
  {
    "id": "excel-82",
    "title": "BOLSA BASURA BRILLEX 50X70",
    "category": "Basureros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 50 \u00b7 Proveedor: Nabil Nasser",
    "price": 690,
    "before": 690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Bolsas-de-basura-70x90-1.jpg",
    "code": "LIMPIEZA",
    "stock": 50
  },
  {
    "id": "excel-83",
    "title": "BOLSA BASURA BRULLEX 70X90",
    "category": "Basureros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 30 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Bolsas-de-basura-70x90-1.jpg",
    "code": "LIMPIEZA",
    "stock": 30
  },
  {
    "id": "excel-84",
    "title": "BOLSA BASURA BRULLEX 80X110",
    "category": "Basureros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 20 \u00b7 Proveedor: Nabil Nasser",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Bolsas-de-basura-80x110-1.jpg",
    "code": "LIMPIEZA",
    "stock": 20
  },
  {
    "id": "excel-85",
    "title": "SUAVIZANTE FUZOL 1 lt",
    "category": "Lavanderia",
    "detail": "Doy Pack \u00b7 Marca: Fuzol \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1390,
    "before": 1390,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_712930-MLA74116143140_012024-O.webp",
    "code": "DOY PACK",
    "stock": 24
  },
  {
    "id": "excel-86",
    "title": "SACAGRASA 500 ml",
    "category": "Lavanderia",
    "detail": "Doy Pack \u00b7 Marca: Sapolio \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Sacagrasa-Brillex.jpg",
    "code": "DOY PACK",
    "stock": 24
  },
  {
    "id": "excel-87",
    "title": "LIMPIA VIDRIOS SAPOLIO 500ml",
    "category": "Vidrios",
    "detail": "Doy Pack \u00b7 Marca: Sapolio \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping-1.jpeg",
    "code": "DOY PACK",
    "stock": 24
  },
  {
    "id": "excel-88",
    "title": "OMO LIQUIDO 400ml",
    "category": "Lavanderia",
    "detail": "Doy Pack \u00b7 Marca: Omo \u00b7 Stock: 15 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_777388-MLA99291234898_112025-F.webp",
    "code": "DOY PACK",
    "stock": 15
  },
  {
    "id": "excel-89",
    "title": "DET RINSO NORMAL 500ML",
    "category": "Lavanderia",
    "detail": "Doy Pack \u00b7 Marca: Rinso \u00b7 Stock: 15 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_884086-MLA81601807146_012025-O.webp",
    "code": "DOY PACK",
    "stock": 15
  },
  {
    "id": "excel-90",
    "title": "LIMPIADOR INODORO SAPOLIO 500ml BOT",
    "category": "Bano",
    "detail": "Limpieza \u00b7 Marca: Sapolio \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1790,
    "before": 1790,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/7751851559102-limpieza-de-espacios-limpiador-desinfectante-sapolio-wc-power-plus-500-ml-puntobarato1671.jpg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-91",
    "title": "TOALLITAS HUMEDAS 70UN BOLSA",
    "category": "Basureros",
    "detail": "Limpieza \u00b7 Marca: Babysec \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/b4665c191b34baf3d0e0fa45dfdd3d1d.jpeg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-92",
    "title": "TOALLITAS HUMEDAS AGUA EMUBABY 4 UN",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Emubaby \u00b7 Stock: 27 \u00b7 Proveedor: Nabil Nasser",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/b4665c191b34baf3d0e0fa45dfdd3d1d.jpeg",
    "code": "LIMPIEZA",
    "stock": 27
  },
  {
    "id": "excel-93",
    "title": "ESCOBILLON NACIONAL",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Nacional \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-94",
    "title": "ESCOBILLON XL c/mango virutex",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Purity \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 3290,
    "before": 3290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-95",
    "title": "TOALLAS HUMEDAS ADULTO BRILLEX 50UN",
    "category": "Otros",
    "detail": "Higiene Personal \u00b7 Marca: Brillex \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1690,
    "before": 1690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/b4665c191b34baf3d0e0fa45dfdd3d1d.jpeg",
    "code": "HIGIENE PERSONAL",
    "stock": 12
  },
  {
    "id": "excel-96",
    "title": "CEPILLO DE BA\u00d1O C/PROTECTOR",
    "category": "Bano",
    "detail": "Limpieza \u00b7 Marca: Aileda \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 1890,
    "before": 1890,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cepillo-dental-Colgate-Super-Frexi-charcoal-600x600.jpg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-97",
    "title": "PERRO DE ROPA X BOLSA",
    "category": "Basureros",
    "detail": "Accesesorios \u00b7 Marca: Teddy \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/PRODUCTOS-WEB-6-45.png",
    "code": "ACCESESORIOS",
    "stock": 10
  },
  {
    "id": "excel-98",
    "title": "ESCOBILLA DE ROPA",
    "category": "Lavanderia",
    "detail": "Accesesorios \u00b7 Marca: Teddy \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-49-350x350-1.jpg",
    "code": "ACCESESORIOS",
    "stock": 10
  },
  {
    "id": "excel-99",
    "title": "GUANTE AMARILLO LATEX",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Brillex \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-100",
    "title": "PASTILLA BA\u00d1O 4UN",
    "category": "Bano",
    "detail": "Limpieza \u00b7 Marca: Aileda \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/07891024034095_512x512.jpg.webp",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-101",
    "title": "PAPEL ALUSA TEDDY 20 MT",
    "category": "Cocina",
    "detail": "Cocina \u00b7 Marca: Teddy \u00b7 Stock: 20 \u00b7 Proveedor: Nabil Nasser",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-148-430x430.jpg",
    "code": "COCINA",
    "stock": 20
  },
  {
    "id": "excel-102",
    "title": "PAPEL ALUMINIO 7,5 MTS",
    "category": "Cocina",
    "detail": "Cocina \u00b7 Marca: Teddy \u00b7 Stock: 20 \u00b7 Proveedor: Nabil Nasser",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/aluminio.jpeg",
    "code": "COCINA",
    "stock": 20
  },
  {
    "id": "excel-103",
    "title": "LUSTRA MUEBLES CREMA 250 ML FRASCO",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Teddy \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Lustramuebles-Crema-Virginia-Tradicional-250.png",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-104",
    "title": "AMBIENTADOR DE PINO",
    "category": "Para tu auto",
    "detail": "Automovil \u00b7 Marca: Pino \u00b7 Stock: 48 \u00b7 Proveedor: Nabil Nasser",
    "price": 1000,
    "before": 1000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/170057-800-auto.png",
    "code": "AUTOMOVIL",
    "stock": 48
  },
  {
    "id": "excel-105",
    "title": "JABON BRILLEX 750 mL",
    "category": "Lavanderia",
    "detail": "Doy Pack \u00b7 Marca: Brillex \u00b7 Stock: 24 \u00b7 Proveedor: Nabil Nasser",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/jabon-brillex-300x300.jpeg",
    "code": "DOY PACK",
    "stock": 24
  },
  {
    "id": "excel-106",
    "title": "RINSO PARA DULUIR 500 M FRASCO",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Rinso \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 3590,
    "before": 3590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_884086-MLA81601807146_012025-O.webp",
    "code": "DETERGENTE",
    "stock": 12
  },
  {
    "id": "excel-107",
    "title": "JABON EN BARRA 75g",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Dove \u00b7 Stock: 48 \u00b7 Proveedor: Nabil Nasser",
    "price": 1190,
    "before": 1190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Dove-Jabon-Beauty-Cream-Bar-600x600.jpg",
    "code": "BELLEZA",
    "stock": 48
  },
  {
    "id": "excel-108",
    "title": "DETERGENTE MATIC 5 lts",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Brillex \u00b7 Stock: 16 \u00b7 Proveedor: Nabil Nasser",
    "price": 3490,
    "before": 3490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-azul-Brillex-600x600.jpg",
    "code": "DETERGENTE",
    "stock": 16
  },
  {
    "id": "excel-109",
    "title": "CLORO BIO 5 LTS",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Bio \u00b7 Stock: 6 \u00b7 Proveedor: Nabil Nasser",
    "price": 1690,
    "before": 1690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-blanco-Brillex-300x300.jpg",
    "code": "LIMPIEZA",
    "stock": 6
  },
  {
    "id": "excel-110",
    "title": "PAPEL HIG DH 20MT 8X6",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Swan \u00b7 Stock: 5 \u00b7 Proveedor: Nabil Nasser",
    "price": 12720,
    "before": 12720,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/papel-higienico-confort-1hoja-almacenero-50mt-und.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 5
  },
  {
    "id": "excel-111",
    "title": "RENDIPLUS 20MT 8X6",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Confort \u00b7 Stock: 5 \u00b7 Proveedor: Nabil Nasser",
    "price": 13520,
    "before": 13520,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/papel-higienico-confort-1hoja-almacenero-50mt-und.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 5
  },
  {
    "id": "excel-112",
    "title": "PAPEL HIGIENICO ELITE 16X3",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Elite \u00b7 Stock: 5 \u00b7 Proveedor: Nabil Nasser",
    "price": 11070,
    "before": 11070,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/52084_2.png",
    "code": "PAPEL HIGIENICO",
    "stock": 5
  },
  {
    "id": "excel-113",
    "title": "PAPEL NOBLE 23MT 8X6",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Noble \u00b7 Stock: 5 \u00b7 Proveedor: Nabil Nasser",
    "price": 14320,
    "before": 14320,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000000697854-UN-01.jpg.webp",
    "code": "PAPEL HIGIENICO",
    "stock": 5
  },
  {
    "id": "excel-114",
    "title": "TOALLA PAPEL NOVA CLASICA 3UN",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: Nova \u00b7 Stock: 3 \u00b7 Proveedor: Nabil Nasser",
    "price": 9990,
    "before": 9990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/nova-clasica.png",
    "code": "TOALLA ROLLO",
    "stock": 3
  },
  {
    "id": "excel-115",
    "title": "TOALLA OVELLA 80 MT DOBLE HOJA XL X6",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: Ovella \u00b7 Stock: 3 \u00b7 Proveedor: Nabil Nasser",
    "price": 14940,
    "before": 14940,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/000000000000674114-UN-01.jpg.jpg.webp",
    "code": "TOALLA ROLLO",
    "stock": 3
  },
  {
    "id": "excel-116",
    "title": "TOALLA PAPEL BASICA 150 MT X4UN",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: S/M \u00b7 Stock: 3 \u00b7 Proveedor: Nabil Nasser",
    "price": 7990,
    "before": 7990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/nova-clasica.png",
    "code": "TOALLA ROLLO",
    "stock": 3
  },
  {
    "id": "excel-117",
    "title": "PAPEL HIGIENICO INDUSTRIAL X 6",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: S/M \u00b7 Stock: 3 \u00b7 Proveedor: Nabil Nasser",
    "price": 5990,
    "before": 5990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/papel-higienico-confort-1hoja-almacenero-50mt-und.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 3
  },
  {
    "id": "excel-118",
    "title": "SERVILLETA 300 UN",
    "category": "Cocina",
    "detail": "Servilleta \u00b7 Marca: Swan \u00b7 Stock: 12 \u00b7 Proveedor: Nabil Nasser",
    "price": 1690,
    "before": 1690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/MOCKUPS-SWAN_Mesa-de-trabajo-1-copia-4-copia-e1759777316408.png",
    "code": "SERVILLETA",
    "stock": 12
  },
  {
    "id": "excel-119",
    "title": "PALA PLASTICA",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/55271-1.jpg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-120",
    "title": "PALA PLASTICA TEDDY 40",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Teddy \u00b7 Stock: 10 \u00b7 Proveedor: Nabil Nasser",
    "price": 2290,
    "before": 2290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/55271-1.jpg",
    "code": "LIMPIEZA",
    "stock": 10
  },
  {
    "id": "excel-121",
    "title": "DETERGENTE DE 5L",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Ro \u00b7 Stock: 50 \u00b7 Proveedor: Multiplus Spa",
    "price": 3850,
    "before": 3850,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-azul-Brillex-600x600.jpg",
    "code": "DETERGENTE",
    "stock": 50
  },
  {
    "id": "excel-122",
    "title": "ESCOBILLON BASICO VIRUTEX PRO",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Virutex \u00b7 Stock: 24 \u00b7 Proveedor: Virutex Chile",
    "price": 2590,
    "before": 2590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-123",
    "title": "ESCOBILLON ECONOMICO IMPEKE",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Impeke \u00b7 Stock: 12 \u00b7 Proveedor: Virutex Chile",
    "price": 1990,
    "before": 1990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-124",
    "title": "MOPA REDONDA DE ALGODON RTO",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Impeke \u00b7 Stock: 24 \u00b7 Proveedor: Virutex Chile",
    "price": 1690,
    "before": 1690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-148-430x430.jpg",
    "code": "LIMPIEZA",
    "stock": 24
  },
  {
    "id": "excel-125",
    "title": "PALO METALICO DE ESCOBA AZUL",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Virutex \u00b7 Stock: 12 \u00b7 Proveedor: Virutex Chile",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-126",
    "title": "ESPONJA PARRILLERA CONASA",
    "category": "Cocina",
    "detail": "Limpieza \u00b7 Marca: Virutex \u00b7 Stock: 12 \u00b7 Proveedor: Virutex Chile",
    "price": 1990,
    "before": 1990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/images.jpeg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-127",
    "title": "PA\u00d1O AMARILLO PISO",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Virutex \u00b7 Stock: 12 \u00b7 Proveedor: Virutex Chile",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Unknown.jpeg",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-128",
    "title": "GUANTE FLOCADO VERDE TALLA L",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 12 \u00b7 Proveedor: Caan",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-129",
    "title": "GUANTE FLOCADO VERDE TALLA S",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 12 \u00b7 Proveedor: Caan",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-130",
    "title": "GUANTE FLOCADO VERDE TALLA M",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 12 \u00b7 Proveedor: Caan",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-131",
    "title": "GUANTE NITRILO NEGRO TEXTURIZADO L",
    "category": "Para tu auto",
    "detail": "Taller \u00b7 Marca: Jwonder \u00b7 Stock: 10 \u00b7 Proveedor: Caan",
    "price": 5990,
    "before": 5990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "TALLER",
    "stock": 10
  },
  {
    "id": "excel-132",
    "title": "GUANTE NITRILO NEGRO TEXTURIZADO L",
    "category": "Para tu auto",
    "detail": "Taller \u00b7 Marca: Jwonder \u00b7 Stock: 10 \u00b7 Proveedor: Caan",
    "price": 5990,
    "before": 5990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_2X_723144-MLC93929224876_102025-T.webp",
    "code": "TALLER",
    "stock": 10
  },
  {
    "id": "excel-133",
    "title": "DESENGRASANTE CONCENTRADO 5L",
    "category": "Para tu auto",
    "detail": "Taller \u00b7 Marca: Caan \u00b7 Stock: 5 \u00b7 Proveedor: Caan",
    "price": 6990,
    "before": 6990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Sacagrasa-Brillex.jpg",
    "code": "TALLER",
    "stock": 5
  },
  {
    "id": "excel-134",
    "title": "JABON MECANICO 5 LT",
    "category": "Para tu auto",
    "detail": "Taller \u00b7 Marca: Caan \u00b7 Stock: 5 \u00b7 Proveedor: Caan",
    "price": 6290,
    "before": 6290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/jabon-liquido-avena-web-300x300.jpg",
    "code": "TALLER",
    "stock": 5
  },
  {
    "id": "excel-135",
    "title": "RENOVADOR DE GOMAS 5L",
    "category": "Para tu auto",
    "detail": "Taller \u00b7 Marca: S/M \u00b7 Stock: 4 \u00b7 Proveedor: Caan",
    "price": 7490,
    "before": 7490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/nova-clasica.png",
    "code": "TALLER",
    "stock": 4
  },
  {
    "id": "excel-136",
    "title": "REMOVEDOR DE SARRO 5L",
    "category": "Bano",
    "detail": "Limpieza \u00b7 Marca: Caan \u00b7 Stock: 4 \u00b7 Proveedor: Caan",
    "price": 6490,
    "before": 6490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/7751851559102-limpieza-de-espacios-limpiador-desinfectante-sapolio-wc-power-plus-500-ml-puntobarato1671.jpg",
    "code": "LIMPIEZA",
    "stock": 4
  },
  {
    "id": "excel-137",
    "title": "BASURERO 30 L AMARILLO PEDAL C/TAPA",
    "category": "Basureros",
    "detail": "Basurero \u00b7 Marca: S/M \u00b7 Stock: 5 \u00b7 Proveedor: Caan",
    "price": 14990,
    "before": 14990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_612800-MLA99895279767_112025-O.webp",
    "code": "BASURERO",
    "stock": 5
  },
  {
    "id": "excel-138",
    "title": "BALDE C/ESTRUJADOR Y MANILLA",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 4 \u00b7 Proveedor: Caan",
    "price": 4990,
    "before": 4990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/23-1-600x600.png",
    "code": "LIMPIEZA",
    "stock": 4
  },
  {
    "id": "excel-139",
    "title": "BALDE DE 11 L",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: S/M \u00b7 Stock: 5 \u00b7 Proveedor: Assady Bamby",
    "price": 2490,
    "before": 2490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/23-1-600x600.png",
    "code": "LIMPIEZA",
    "stock": 5
  },
  {
    "id": "excel-140",
    "title": "SET DE PERRO ROPA PLASTICO 24PZS GDE",
    "category": "Lavanderia",
    "detail": "Accesesorios \u00b7 Marca: S/M \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 990,
    "before": 990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/PRODUCTOS-WEB-6-45.png",
    "code": "ACCESESORIOS",
    "stock": 4
  },
  {
    "id": "excel-141",
    "title": "COLGADOR OVALADO",
    "category": "Otros",
    "detail": "Accesesorios \u00b7 Marca: S/M \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 2190,
    "before": 2190,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/PRODUCTOS-WEB-6-45.png",
    "code": "ACCESESORIOS",
    "stock": 4
  },
  {
    "id": "excel-142",
    "title": "CEPILLO DE ESCOBA C/MANGO VIC",
    "category": "Piso",
    "detail": "Accesesorios \u00b7 Marca: Vic \u00b7 Stock: 6 \u00b7 Proveedor: Assady Bamby",
    "price": 1890,
    "before": 1890,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cepillo-dental-Colgate-Super-Frexi-charcoal-600x600.jpg",
    "code": "ACCESESORIOS",
    "stock": 6
  },
  {
    "id": "excel-143",
    "title": "ESCOBILLA COLOR MANGO VIC",
    "category": "Otros",
    "detail": "Accesesorios \u00b7 Marca: Vic \u00b7 Stock: 10 \u00b7 Proveedor: Assady Bamby",
    "price": 890,
    "before": 890,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-49-350x350-1.jpg",
    "code": "ACCESESORIOS",
    "stock": 10
  },
  {
    "id": "excel-144",
    "title": "ESCOBILLON PURITY MANGO MADERA",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Purity \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 2890,
    "before": 2890,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1030313-CHAITAN201.JPG",
    "code": "LIMPIEZA",
    "stock": 4
  },
  {
    "id": "excel-145",
    "title": "BASURERO PEDAL 10L",
    "category": "Basureros",
    "detail": "Basurero \u00b7 Marca: S/M \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 6990,
    "before": 6990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_612800-MLA99895279767_112025-O.webp",
    "code": "BASURERO",
    "stock": 4
  },
  {
    "id": "excel-146",
    "title": "BASURERO 60 LTS C/TAPA",
    "category": "Basureros",
    "detail": "Basurero \u00b7 Marca: Genius \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 15990,
    "before": 15990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_612800-MLA99895279767_112025-O.webp",
    "code": "BASURERO",
    "stock": 4
  },
  {
    "id": "excel-147",
    "title": "CANASTO CON MANILLA",
    "category": "Otros",
    "detail": "Accesesorios \u00b7 Marca: Dutty \u00b7 Stock: 4 \u00b7 Proveedor: Assady Bamby",
    "price": 4990,
    "before": 4990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/23-1-600x600.png",
    "code": "ACCESESORIOS",
    "stock": 4
  },
  {
    "id": "excel-148",
    "title": "BASURERO CON TAPA ABATIBLE",
    "category": "Basureros",
    "detail": "Basurero \u00b7 Marca: S/M \u00b7 Stock: 5 \u00b7 Proveedor: Assady Bamby",
    "price": 4990,
    "before": 4990,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_612800-MLA99895279767_112025-O.webp",
    "code": "BASURERO",
    "stock": 5
  },
  {
    "id": "excel-149",
    "title": "SHAMPOO SEDAL 340ML",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Sedal \u00b7 Stock: 24 \u00b7 Proveedor: Multiplus Spa",
    "price": 2290,
    "before": 2290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/330x570SHAMPOOFRASCO.png",
    "code": "BELLEZA",
    "stock": 24
  },
  {
    "id": "excel-150",
    "title": "TRAPERO HUMEDO MULTIPISOS",
    "category": "Piso",
    "detail": "Limpieza \u00b7 Marca: Rituz \u00b7 Stock: 12 \u00b7 Proveedor: Multiplus Spa",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/010309-BRILLEX-TRAPERO-HUMEDO-LIMON-7-UNID.jpg.avif",
    "code": "LIMPIEZA",
    "stock": 12
  },
  {
    "id": "excel-151",
    "title": "CEPILLO ADULTO X13 UN",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Oral B \u00b7 Stock: 1 \u00b7 Proveedor: Multiplus Spa",
    "price": 9480,
    "before": 9480,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Cepillo-dental-Colgate-Super-Frexi-charcoal-600x600.jpg",
    "code": "BUCAL",
    "stock": 1
  },
  {
    "id": "excel-152",
    "title": "CEPILLO NI\u00d1O KIDS X 12 UN",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Oral B \u00b7 Stock: 1 \u00b7 Proveedor: Multiplus Spa",
    "price": 7080,
    "before": 7080,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/essere_kids.png",
    "code": "BUCAL",
    "stock": 1
  },
  {
    "id": "excel-153",
    "title": "JABON PROTEX X6",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Protex \u00b7 Stock: 3 \u00b7 Proveedor: Multiplus Spa",
    "price": 5940,
    "before": 5940,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/jabon-liquido-avena-web-300x300.jpg",
    "code": "BELLEZA",
    "stock": 3
  },
  {
    "id": "excel-154",
    "title": "BIO FRESCURA NARANJO 800g",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Bio \u00b7 Stock: 18 \u00b7 Proveedor: Multiplus Spa",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Detergente-naranjo-Brillex-1-300x300.jpg",
    "code": "DETERGENTE",
    "stock": 18
  },
  {
    "id": "excel-155",
    "title": "OMO LAVADO MANO 400g (SURTIDO)",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Omo \u00b7 Stock: 30 \u00b7 Proveedor: Multiplus Spa",
    "price": 1290,
    "before": 1290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_Q_NP_777388-MLA99291234898_112025-F.webp",
    "code": "DETERGENTE",
    "stock": 30
  },
  {
    "id": "excel-156",
    "title": "MINI ABOLENGO 80 PAQUETES X 40 UN",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Abolengo \u00b7 Stock: 1 \u00b7 Proveedor: Multiplus Spa",
    "price": 28000,
    "before": 28000,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Unknown.jpeg",
    "code": "LIMPIEZA",
    "stock": 1
  },
  {
    "id": "excel-157",
    "title": "ARIEL LIQUIDO 1,8L",
    "category": "Lavanderia",
    "detail": "Detergente \u00b7 Marca: Ariel \u00b7 Stock: 6 \u00b7 Proveedor: Multiplus Spa",
    "price": 7290,
    "before": 7290,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_612800-MLA99895279767_112025-O.webp",
    "code": "DETERGENTE",
    "stock": 6
  },
  {
    "id": "excel-158",
    "title": "TOALLA COCINA CON DISE\u00d1O X 6UN",
    "category": "Cocina",
    "detail": "Toalla Rollo \u00b7 Marca: Like \u00b7 Stock: 2 \u00b7 Proveedor: Multiplus Spa",
    "price": 17940,
    "before": 17940,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/nova-clasica.png",
    "code": "TOALLA ROLLO",
    "stock": 2
  },
  {
    "id": "excel-159",
    "title": "P. HIGIENICO 50M DOBLE HOJA 32 UN (X8PA)",
    "category": "Papel higienico",
    "detail": "Papel Higienico \u00b7 Marca: Tork \u00b7 Stock: 3 \u00b7 Proveedor: Multiplus Spa",
    "price": 18320,
    "before": 18320,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/papel-higienico-confort-1hoja-almacenero-50mt-und.jpg",
    "code": "PAPEL HIGIENICO",
    "stock": 3
  },
  {
    "id": "excel-160",
    "title": "TOALLA TITAN X6",
    "category": "Papel higienico",
    "detail": "Toalla Rollo \u00b7 Marca: Winroll \u00b7 Stock: 4 \u00b7 Proveedor: Comercial Castro",
    "price": 22140,
    "before": 22140,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/52084_2.png",
    "code": "TOALLA ROLLO",
    "stock": 4
  },
  {
    "id": "excel-161",
    "title": "VIRUTILLA FINA PACK 6UN",
    "category": "Otros",
    "detail": "Limpieza \u00b7 Marca: Key \u00b7 Stock: 20 \u00b7 Proveedor: Dist Astorga Spa",
    "price": 690,
    "before": 690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/shopping.jpeg",
    "code": "LIMPIEZA",
    "stock": 20
  },
  {
    "id": "excel-162",
    "title": "PLUMERO DE ALGODON",
    "category": "Otros",
    "detail": "Accesesorios \u00b7 Marca: S/M \u00b7 Stock: 24 \u00b7 Proveedor: Dist Astorga Spa",
    "price": 1490,
    "before": 1490,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/1459.jpg",
    "code": "ACCESESORIOS",
    "stock": 24
  },
  {
    "id": "excel-163",
    "title": "GILETTE TIRA DE 12 UN 3HOJAS",
    "category": "Higiene personal",
    "detail": "Belleza \u00b7 Marca: Gilette \u00b7 Stock: 1 \u00b7 Proveedor: Dist Astorga Spa",
    "price": 15480,
    "before": 15480,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/D_NQ_NP_611711-MLC92295719982_092025-O.webp",
    "code": "BELLEZA",
    "stock": 1
  },
  {
    "id": "excel-164",
    "title": "CEPILLAO DIENTES KIDS PACK 3 UN",
    "category": "Higiene personal",
    "detail": "Bucal \u00b7 Marca: Oral B \u00b7 Stock: 6 \u00b7 Proveedor: Dist Astorga Spa",
    "price": 1590,
    "before": 1590,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/essere_kids.png",
    "code": "BUCAL",
    "stock": 6
  },
  {
    "id": "excel-165",
    "title": "SOPAPO C/BASE",
    "category": "Otros",
    "detail": "Accesesorios \u00b7 Marca: Aileda \u00b7 Stock: 6 \u00b7 Proveedor: Dist Astorga Spa",
    "price": 3690,
    "before": 3690,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/Teddy-49-350x350-1.jpg",
    "code": "ACCESESORIOS",
    "stock": 6
  },
  {
    "id": "excel-166",
    "title": "PISO DE GOMA ESTOPEROL 3MM X 1M",
    "category": "Piso",
    "detail": "Accesesorios \u00b7 Marca: Qrubber \u00b7 Stock: 20 \u00b7 Proveedor: Qrubber",
    "price": 9900,
    "before": 9900,
    "discount": "",
    "hotSale": false,
    "image": "goesca photos/170057-800-auto.png",
    "code": "ACCESESORIOS",
    "stock": 20
  }
];

function syncCatalogVersion() {
  if (localStorage.getItem("goesca-catalog-version") === CATALOG_VERSION) {
    return;
  }

  localStorage.removeItem("goesca-product-changes");
  localStorage.removeItem("goesca-custom-products");
  localStorage.removeItem("goesca-cart");
  localStorage.setItem("goesca-catalog-version", CATALOG_VERSION);
}

function getSavedProductChanges() {
  try {
    return JSON.parse(localStorage.getItem("goesca-product-changes") || "{}");
  } catch {
    return {};
  }
}

function getCustomProducts() {
  try {
    return JSON.parse(localStorage.getItem("goesca-custom-products") || "[]");
  } catch {
    return [];
  }
}

function normalizeCategory(category) {
  if (category === "Confort") return "Papel higienico";
  if (category === "Liquidos" || category === "Guantes") return "Otros";
  return category;
}

function applyProductChanges(product) {
  const changes = getSavedProductChanges()[product.id];

  if (!changes) {
    return {
      ...product,
      category: normalizeCategory(product.category),
    };
  }

  const price = Number.parseInt(changes.price, 10);
  const before = Number.parseInt(changes.before, 10);

  return {
    ...product,
    title: typeof changes.title === "string" && changes.title.trim() ? changes.title.trim() : product.title,
    image: typeof changes.image === "string" && changes.image.trim() ? changes.image.trim() : product.image,
    category: normalizeCategory(typeof changes.category === "string" && changes.category.trim() ? changes.category.trim() : product.category),
    price: Number.isNaN(price) ? product.price : price,
    before: Number.isNaN(before) ? product.before : before,
    discount: typeof changes.discount === "string" ? changes.discount : product.discount,
    hotSale: typeof changes.hotSale === "boolean" ? changes.hotSale : product.hotSale,
  };
}

syncCatalogVersion();

window.goescaProductPhotoFiles = [];
window.goescaProductChanges = getSavedProductChanges();
window.goescaProducts = [
  ...baseProducts.map(applyProductChanges),
  ...getCustomProducts().map(applyProductChanges),
];
window.goescaCategories = [
  "Todos",
  "Ofertas",
  "Para tu auto",
  "Piso",
  "Vidrios",
  "Bano",
  "Cocina",
  "Lavanderia",
  "Ambientales",
  "Higiene personal",
  "Basureros",
  "Papel higienico",
  "Otros"
];
